apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finops-scaler.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "finops-scaler.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "finops-scaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "finops-scaler.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.config.metricsPort | quote }}
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ include "finops-scaler.fullname" . }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "finops-scaler.fullname" . }}-config
          ports:
            - name: metrics
              containerPort: {{ .Values.config.metricsPort | int }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            readOnlyRootFilesystem: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
